import {
  EventTone,
  StaffRole,
  type CustomerArchetype,
  type Drink,
  type GameCatalog,
  type RandomEvent,
  type Regular,
  type StaffArchetype,
  type Upgrade,
} from './types';

/**
 * Starter named regulars. Loyalty starts at 0 (neutral); spriteId reuses
 * archetype art for now — Wheezer / Rook share the dive_regular sprite,
 * Mike shares rowdy_college_kid, Doc reuses lost_tourist as a stand-in.
 */
export const startingRegulars: Regular[] = [
  { id: 'reg_wheezer', displayName: 'Wheezer', archetypeId: 'dive_regular',      spriteId: 'dive_regular',      loyalty: 0, lastSeenDay: 0 },
  { id: 'reg_rook',    displayName: 'Rook',    archetypeId: 'dive_regular',      spriteId: 'dive_regular',      loyalty: 0, lastSeenDay: 0 },
  { id: 'reg_mike',    displayName: 'Mike',    archetypeId: 'rowdy_college_kid', spriteId: 'rowdy_college_kid', loyalty: 0, lastSeenDay: 0 },
  { id: 'reg_doc',     displayName: 'Doc',     archetypeId: 'lost_tourist',      spriteId: 'lost_tourist',      loyalty: 0, lastSeenDay: 0 },
];

export const drinks: Drink[] = [
  { id: 'pbr', displayName: 'PBR', costToMake: 1, suggestedPrice: 4, prepTicks: 1, quality: 0.3 },
  { id: 'whiskey_sour', displayName: 'Whiskey Sour', costToMake: 3, suggestedPrice: 9, prepTicks: 2, quality: 0.7 },
  { id: 'house_special', displayName: 'House Special', costToMake: 4, suggestedPrice: 12, prepTicks: 2, quality: 0.85 },
];

export const customerArchetypes: CustomerArchetype[] = [
  {
    id: 'dive_regular',
    displayName: 'Dive Regular',
    emoji: '🧔',
    preferredDrinkIds: ['pbr'],
    spawnWeight: 0.45,
    tipMultiplier: 0.1,
    patienceTicks: 5,
    mishapChance: 0.04,
    repInfluence: 1,
    flavorText: 'Sat at the same stool since 1998. Nods at no one in particular.',
    phaseSpawnMultiplier: { early: 1.3, prime: 1.0, lastCall: 0.7 },
  },
  {
    id: 'lost_tourist',
    displayName: 'Lost Tourist',
    emoji: '🧳',
    preferredDrinkIds: ['house_special'],
    spawnWeight: 0.18,
    tipMultiplier: 0.25,
    patienceTicks: 3,
    mishapChance: 0.02,
    repInfluence: 0.5,
    flavorText: 'Wandered in looking for a museum. Tips well out of confusion.',
  },
  {
    id: 'rowdy_college_kid',
    displayName: 'Rowdy College Kid',
    emoji: '🎓',
    preferredDrinkIds: ['pbr', 'whiskey_sour'],
    spawnWeight: 0.25,
    tipMultiplier: 0.05,
    patienceTicks: 2,
    mishapChance: 0.18,
    repInfluence: 0.7,
    flavorText: 'Loud, sticky, and weirdly loyal. Will start a chant at any moment.',
    phaseSpawnMultiplier: { early: 0.5, prime: 1.0, lastCall: 1.5 },
  },
  {
    id: 'date_night_couple',
    displayName: 'Date-Night Couple',
    emoji: '💑',
    preferredDrinkIds: ['whiskey_sour', 'house_special'],
    spawnWeight: 0.12,
    tipMultiplier: 0.30,
    patienceTicks: 5,
    mishapChance: 0.01,
    repInfluence: 1.5,
    flavorText: 'Holding hands across the bar. Splitting an appetizer they barely touch.',
    minReputation: 15,
    phaseSpawnMultiplier: { early: 0.5, prime: 1.5, lastCall: 1.0 },
  },
  {
    id: 'yelp_reviewer',
    displayName: 'Yelp Reviewer',
    emoji: '📝',
    preferredDrinkIds: ['house_special'],
    spawnWeight: 0.06,
    tipMultiplier: 0.20,
    patienceTicks: 4,
    mishapChance: 0.10,
    repInfluence: 4,
    flavorText: 'Photographing the drink before tasting it. Frowning thoughtfully.',
    minReputation: 35,
  },
  {
    id: 'wedding_party',
    displayName: 'Wedding Party',
    emoji: '👰',
    preferredDrinkIds: ['pbr', 'whiskey_sour', 'house_special'],
    spawnWeight: 0.20,
    tipMultiplier: 0.15,
    patienceTicks: 3,
    mishapChance: 0.08,
    repInfluence: 0.8,
    flavorText: "Reception ran out of bar tab. They've got nowhere else to be.",
    minReputation: 60,
    phaseSpawnMultiplier: { early: 0.2, prime: 1.0, lastCall: 2.0 },
  },
];

export const staffArchetypes: StaffArchetype[] = [
  {
    id: 'marv_bartender',
    displayName: 'Marv',
    role: StaffRole.Bartender,
    baseWagePerDay: 30,
    hireCost: 0,
    traits: ['Surly', 'Quick'],
    speed: 0.6,
    charm: 0.2,
    reliability: 0.8,
    flavorText: "Pours a beer in 4 seconds flat. Never says hello.",
    emoji: '🧑‍🍳',
  },
  {
    id: 'skeeter_bouncer',
    displayName: 'Skeeter',
    role: StaffRole.Bouncer,
    baseWagePerDay: 40,
    hireCost: 120,
    traits: ['Charming'],
    speed: 0.4,
    charm: 0.6,
    reliability: 0.9,
    flavorText: 'Built like a fridge. Knows everybody by their first name.',
    emoji: '🦺',
  },
  {
    id: 'dee_server',
    displayName: 'Dee',
    role: StaffRole.Server,
    baseWagePerDay: 35,
    hireCost: 100,
    traits: ['Chatty', 'Klutz'],
    speed: 0.5,
    charm: 0.85,
    reliability: 0.6,
    flavorText: "Could chat a mannequin into ordering a third. Drops one tray in five.",
    emoji: '💁',
  },
];

export const events: RandomEvent[] = [
  {
    id: 'jukebox_eats_quarter',
    displayName: 'Jukebox eats a quarter',
    tone: EventTone.Whimsical,
    perTickChance: 0.04,
    cashDelta: 0,
    repDelta: 0,
    narrative: 'The jukebox eats a quarter. The bar groans in unison.',
  },
  {
    id: 'singalong',
    displayName: 'Singalong erupts',
    tone: EventTone.Lucky,
    perTickChance: 0.03,
    cashDelta: 8,
    repDelta: 1,
    narrative: 'Someone starts singing Sweet Caroline. The whole bar joins in. (+$8, +1 rep)',
  },
  {
    id: 'health_inspector',
    displayName: 'Health inspector drops in',
    tone: EventTone.Crisis,
    perTickChance: 0.015,
    cashDelta: -25,
    repDelta: -1,
    narrative: 'A health inspector drops in. (-$25, -1 rep)',
    minReputation: 0,
    decisionPrompt: 'Health inspector wants a word — what’s the call?',
    decisionOptions: [
      {
        key: 'pour',
        label: 'Take Fine',
        cashDelta: -25,
        repDelta: -1,
        narrative: 'Marv takes the fine and says nothing. (-$25, -1 rep)',
        isDefault: true,
      },
      {
        key: 'ring-up',
        label: 'Bribe',
        requires: 'cash-50',
        cashDelta: -50,
        repDelta: 0,
        narrative: 'A folded bill, a quiet handshake. The inspector finds nothing wrong. (-$50)',
      },
      {
        key: 'door',
        label: 'Charm',
        requires: 'charming-on-floor',
        cashDelta: -5,
        repDelta: 1,
        narrative: 'A free drink and a story — they leave smiling. (-$5, +1 rep)',
      },
    ],
  },
  {
    id: 'bar_fight',
    displayName: 'Two regulars start scrapping',
    tone: EventTone.Crisis,
    perTickChance: 0.012,
    cashDelta: -15,
    repDelta: -1,
    narrative: 'Two regulars start scrapping at the corner table. (-$15, -1 rep)',
  },
  {
    id: 'toilet_overflows',
    displayName: 'Toilet overflows',
    tone: EventTone.Mishap,
    perTickChance: 0.025,
    cashDelta: -10,
    repDelta: -1,
    narrative: 'The bathroom situation deteriorates. (-$10, -1 rep)',
  },
  {
    id: 'regular_brings_friends',
    displayName: 'A regular brings friends',
    tone: EventTone.Lucky,
    perTickChance: 0.04,
    cashDelta: 15,
    repDelta: 1,
    narrative: 'A regular brings three friends from out of town. (+$15, +1 rep)',
  },
];

export const upgrades: Upgrade[] = [
  {
    id: 'better_stools',
    displayName: 'Better Stools',
    cost: 200,
    spawnRateMultiplier: 1.05,
    repPerShift: 1,
    tipBonus: 0,
    flavorText: 'Your patrons no longer leave with a permanent limp.',
  },
  {
    id: 'new_sign',
    displayName: 'New Sign',
    cost: 300,
    spawnRateMultiplier: 1.15,
    repPerShift: 0,
    tipBonus: 0,
    flavorText: 'People can now find the place from the street.',
  },
];

export const catalog: GameCatalog = {
  drinks,
  staffArchetypes,
  customerArchetypes,
  events,
  upgrades,
};
